// Code generated by protoc-gen-go-errors. DO NOT EDIT.

package v1

import (
	fmt "fmt"
	errors "github.com/go-kratos/kratos/v2/errors"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
const _ = errors.SupportPackageIsVersion1

// 为某个枚举单独设置错误码
func IsNeedLogin(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_NEED_LOGIN.String() && e.Code == 401
}

// 为某个枚举单独设置错误码
func ErrorNeedLogin(format string, args ...interface{}) *errors.Error {
	return errors.New(401, ErrorReason_NEED_LOGIN.String(), fmt.Sprintf(format, args...))
}

func IsDbFailed(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_DB_FAILED.String() && e.Code == 500
}

func ErrorDbFailed(format string, args ...interface{}) *errors.Error {
	return errors.New(500, ErrorReason_DB_FAILED.String(), fmt.Sprintf(format, args...))
}

func IsOrderReviewed(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_ORDER_REVIEWED.String() && e.Code == 405
}

func ErrorOrderReviewed(format string, args ...interface{}) *errors.Error {
	return errors.New(405, ErrorReason_ORDER_REVIEWED.String(), fmt.Sprintf(format, args...))
}

func IsReviewNotFound(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_Review_NOT_FOUND.String() && e.Code == 404
}

func ErrorReviewNotFound(format string, args ...interface{}) *errors.Error {
	return errors.New(404, ErrorReason_Review_NOT_FOUND.String(), fmt.Sprintf(format, args...))
}

func IsReviewAlreadyReplied(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_Review_ALREADY_REPLIED.String() && e.Code == 406
}

func ErrorReviewAlreadyReplied(format string, args ...interface{}) *errors.Error {
	return errors.New(406, ErrorReason_Review_ALREADY_REPLIED.String(), fmt.Sprintf(format, args...))
}

func IsHorizontalPrivilegeEscalation(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_HORIZONTAL_PRIVILEGE_ESCALATION.String() && e.Code == 407
}

func ErrorHorizontalPrivilegeEscalation(format string, args ...interface{}) *errors.Error {
	return errors.New(407, ErrorReason_HORIZONTAL_PRIVILEGE_ESCALATION.String(), fmt.Sprintf(format, args...))
}
